# Generated by Django 5.2.1 on 2025-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_c_name_product_category_product_p_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_phone', models.IntegerField(max_length=10)),
                ('cust_email', models.EmailField(max_length=255, unique=True)),
                ('cust_username', models.CharField(max_length=255)),
                ('cust_password', models.TextField(max_length=255)),
            ],
        ),
    ]
